id: AC0D78858
title: 'MSV 2,01: Vinayavibhaṅga'
type: translation
pechas:
- I94FA0E50
- IC6FC6472
source_metadata:
  languages:
  - bo
  datatype: PlainText
  created_at: 2023-02-10 00:06:01.441717
  last_modified_at: 2023-02-10 00:06:01.441733
alignment_to_base:
  I94FA0E50/33E9: 5ABF
  IC6FC6472/00EE: 5ABF
